api = "0.2"

[buildpack]
  id = "dapper-devops/nginx"
  name = "Nginx Buildpack"
  version  = "2020.12.0"
  homepage = "https://gitlab.com/watheia/dapper-devops/buildpacks/nginx"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/configure", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.19.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-05-01T00:00:00Z"
    id = "nginx"
    name = "Nginx Server"
    sha256 = "d9e0e4e0a30b383d172bc557d58794bbd97b742686656d8400ab0f4bc4c52e25"
    source = "http://nginx.org/download/nginx-1.19.6.tar.gz"
    source_sha256 = "b11195a02b1d3285ddf2987e02c6b6d28df41bb1b1dd25f33542848ef4fc33b5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "dev.watheia.stacks.tiny", "dev.watheia.stacks.dendrite"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/nginx/nginx_1.19.6_linux_x64_cflinuxfs3_d9e0e4e0.tgz"
    version = "1.19.6"

  [metadata.version-lines]
    latest = "1.19.*"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "dev.watheia.stacks.slim"

[[stacks]]
id = "dev.watheia.stacks.dendrite"